### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by canalpozuelo** [Oliv3rs/Alexa-Radio-Skill#2]
Buenas Tardes.
Estoy probando tu codigo directamente sin modificarlo pero da un error en Alexa, a ti te ha funcionado correctamente ?

Se ha producido un error con la respuesta de la Skill que has pedido

**Comment by Oliv3rs** [comment]
El código funciona de manera correcta, verifica si activaste la directiva de audio player

**Comment by canalpozuelo** [comment]
Si esta activa

![imagen](https://user-images.githubusercontent.com/58640921/95024073-266a9880-0681-11eb-84db-51fe435080d0.png)

**Comment by canalpozuelo** [comment]
Por si estoy realizando algo erroneo

Pongo el codigo exactamente como lo tienes en Intens JSON editor y pego el codigo, luego le doy a build, posteriormente activo la directiva de audio player (que esta activada) luego me voy a Code y booro todo los archivos y debajo de la carpeta Skill Code creo el archivo index.js y pego el codigo tuyo directamente, luego doy a test y me sale el error que te indique. me estoy saltando algun paso ?

**Comment by Oliv3rs** [comment]
La URL del stream ya la cambiaste? La que está en el código es una URL de ejemplo por lo cual no existe y por clara razón no funcionará la skill
